[units]          
angle = 'deg'        # Units used for angles
length = 'mm'        # units used for lengths

[panel]              # Panel parameters
number = 12          # number of panels in  the arena
omitted = []         # list  of omitted panels
offset_angle = 0     # offset angle for panel position
width = 40.5         # width of panels 
depth = 15           # depth from front to back of panels 

[pins]               # Header pin parameters
number = 15          # number of header pins
pitch = 2.54         # pitch (distance) between header pins
depth = 13.1         # depth from front to header pins 
omitted = []         # pins omitted from header

[pcb]
size_x = 228.6       # PCB size in x-dimension
size_y = 228.6       # PCB size in y-dimension
center_x = 177.8     # PCB center x-coordinate
center_y = 177.8     # PCB center y-coordinate 
line_width = 0.3     # PCB edge line width
cutout_diam = 157.0  # Inside hole radius
add_boundary = false # Add PCB boundary 
add_cutout = false   # Add PCB internal cutout

[pcb.panel]
ref_prefix = 'P'     # Symbol prefix for panel headers
ref_start = 1        # Start number for panel headers

[pcb.relative]
model = 1            # Model for relative component placement

# Lists of relative components for placement 
1  =  ['C47', 'C48', 'C49', 'C50', 'U36', 'U37', 'U38', 'U39', 'R127', 'R128', 'R129', 'R130', 'R131', 'R132', 'R133', 'R134', 'R223', 'C95' ]               
2  =  ['C51', 'C52', 'C53', 'C54', 'U40', 'U41', 'U42', 'U43', 'R135', 'R136', 'R137', 'R138', 'R139', 'R140', 'R141', 'R142', 'R224', 'C96' ]               
3  =  ['C55', 'C56', 'C57', 'C58', 'U44', 'U45', 'U46', 'U47', 'R143', 'R144', 'R145', 'R146', 'R147', 'R148', 'R149', 'R150', 'R225', 'C97' ]               
4  =  ['C59', 'C60', 'C61', 'C62', 'U48', 'U49', 'U50', 'U51', 'R151', 'R152', 'R153', 'R154', 'R155', 'R156', 'R157', 'R158', 'R226', 'C98' ]               
5  =  ['C63', 'C64', 'C65', 'C66', 'U52', 'U53', 'U54', 'U55', 'R159', 'R160', 'R161', 'R162', 'R163', 'R164', 'R165', 'R166', 'R227', 'C99' ]               
6  =  ['C67', 'C68', 'C69', 'C70', 'U56', 'U57', 'U58', 'U59', 'R167', 'R168', 'R169', 'R170', 'R171', 'R172', 'R173', 'R174', 'R228', 'C100']               
7  =  ['C71', 'C72', 'C73', 'C74', 'U60', 'U61', 'U62', 'U63', 'R175', 'R176', 'R177', 'R178', 'R179', 'R180', 'R181', 'R182', 'R229', 'C101']               
8  =  ['C75', 'C76', 'C77', 'C78', 'U64', 'U65', 'U66', 'U67', 'R183', 'R184', 'R185', 'R186', 'R187', 'R188', 'R189', 'R190', 'R230', 'C102']               
9  =  ['C79', 'C80', 'C81', 'C82', 'U68', 'U69', 'U70', 'U71', 'R191', 'R192', 'R193', 'R194', 'R195', 'R196', 'R197', 'R198', 'R231', 'C103']               
10 =  ['C83', 'C84', 'C85', 'C86', 'U72', 'U73', 'U74', 'U75', 'R199', 'R200', 'R201', 'R202', 'R203', 'R204', 'R205', 'R206', 'R232', 'C104']               
11 =  ['C87', 'C88', 'C89', 'C90', 'U76', 'U77', 'U78', 'U79', 'R207', 'R208', 'R209', 'R210', 'R211', 'R212', 'R213', 'R214', 'R233', 'C105']               
12 =  ['C91', 'C92', 'C93', 'C94', 'U80', 'U81', 'U82', 'U83', 'R215', 'R216', 'R217', 'R218', 'R219', 'R220', 'R221', 'R222', 'R234', 'C106']               



