[units]          
angle = 'deg'        # Units used for angles
length = 'mm'        # units used for lengths

[panel]              # Panel parameters
number = 12          # number of panels in  the arena
omitted = []         # list  of omitted panels
offset_angle = 0     # offset angle for panel position
width = 40.5         # width of panels 
depth = 15           # depth from front to back of panels 

[pins]               # Header pin parameters
number = 15          # number of header pins
pitch = 2.54         # pitch (distance) between header pins
depth = 13.1         # depth from front to header pins 
omitted = []         # pins omitted from header

[pcb]
size_x = 228.6       # PCB size in x-dimension
size_y = 228.6       # PCB size in y-dimension
center_x = 177.8     # PCB center x-coordinate
center_y = 177.8     # PCB center y-coordinate 
line_width = 0.3     # PCB edge line width
cutout_diam = 157.0  # Inside hole radius
add_boundary = false # Add PCB boundary 
add_cutout = false   # Add PCB internal cutout

[pcb.panel]
ref_prefix = 'P'     # Symbol prefix for panel headers
ref_start = 1        # Start number for panel headers
pcb_side = 'back'    # side of pcb on which to place component

[pcb.relative]
model = 1            # Model for relative component placement

# Lists of relative components for placement 
1  =  [ 'C1', 'C13']               
2  =  [ 'C2', 'C14']               
3  =  [ 'C3', 'C15']               
4  =  [ 'C4', 'C16']               
5  =  [ 'C5', 'C17']               
6  =  [ 'C6', 'C18']               
7  =  [ 'C7', 'C19']               
8  =  [ 'C8', 'C20']               
9  =  [ 'C9', 'C21']               
10 =  ['C10', 'C22']               
11 =  ['C11', 'C23']               
12 =  ['C12', 'C24']               



